version: 2.1

workflows:
   build:
     jobs:
       - build:
           context: test-context	

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-browsers
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo $MY_ENV_VAR
      - checkout
      - run:
          name: Push submission repository
          command: >-
            ls $CIRCLE_WORKING_DIRECTORY
            git push https://$MY_CRED_VAR@github.com/recruitmenttest/test.git $CIRCLE_WORKING_DIRECTORY
